---

# Push EVPN/VXLAN switch configs to EOS10,11,14,15,20,21

- name: Push switch configs
  connection: httpapi
  hosts: all
  gather_facts: no
  become: yes
  become_method: enable

  vars:
    ansible_python_interpreter: $(which python)
    config_dir: "{{ playbook_dir }}/../avd_configs/"

  tasks:

    - name: "Configs from {{ config_dir }}"
      eos_config:
        src: "{{ config_dir }}{{ inventory_hostname }}.cfg"
        replace: config
        save_when: changed
