---
- name: Reset Topology to Base
  hosts: cvp
  connection: local
  gather_facts: no

  collections:
    - arista.cvp
    - arista.avd

  tasks:

    # Task will build/update Container Topology and Attach configlets to the Containers
    - name: "Updating Container Topology"
      cv_container_v3:
        topology: "{{ RESET_CVP_CONTAINERS }}"
        apply_mode: strict
      register: RESET_CVP_CONTAINERS_RESULT

    # Task will update Device configlet list and which container the device is connected
    - name: "Updating Devices"
      cv_device_v3:
        devices: "{{ RESET_CVP_DEVICES }}"
        state: present
        apply_mode: strict
      register: RESET_CVP_DEVICES_RESULT

    # Tasl will Execute Pending Tasks
    - name: Execute all tasks registered in cvp_configlets variable
      cv_task_v3:
        tasks: "{{ RESET_CVP_DEVICES_RESULT.taskIds }}"

