---
- name: Reset Topology to Base
  hosts: cvp
  connection: local
  gather_facts: no

  collections:
    - arista.cvp
    - arista.avd

  tasks:

    # # Upload configlets from a directory
    # - name: "Upload configlets to CVP {{ inventory_hostname }}"
    #   tags: [ upload, full ]
    #   import_role:
    #       name: arista.avd.cvp_configlet_upload
    #   vars:
    #     configlet_directory: 'cvp_configlets'
    #     file_extension: 'cfg'
    #     configlets_cvp_prefix: 'DEMO'

    # Task will build/update Container Topology and Attach configlets to the Containers
    - name: "Updating Container Topology"
      tags: [ update, full ]
      cv_container_v3:
        topology: "{{ RESET_CVP_CONTAINERS }}"
        apply_mode: strict
      register: RESET_CVP_CONTAINERS_RESULT

    # Task will update Device configlet list and which container the device is connected
    - name: "Updating Devices"
      tags: [ update, full ]
      cv_device_v3:
        devices: "{{ RESET_CVP_DEVICES }}"
        state: present
        apply_mode: strict
      register: RESET_CVP_DEVICES_RESULT

    # - name: Execute all tasks registered in cvp_configlets variable
    #   tags: [execute, never]
    #   cv_task_v3:
    #     tasks: "{{ RESET_CVP_DEVICES_RESULT.taskIds }}"

