###############################################################
#
# Container Topology:
# Add new section for each container you want to manage configlets
# Required fields:
#  Key:
#    name:
#    parent_container:
#    configlets: [list]
#
###############################################################

CVP_CONTAINERS:
  BASE:
    parentContainerName: Tenant
  DEMO:
    parentContainerName: Tenant
  LEAFS:
    parentContainerName: DEMO
  SPINES:
    parentContainerName: DEMO